# This is a basic workflow to help you get started with Actions

name: CI to Docker Package

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
     version:
      description: 'Versione'
      required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_and_push:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set env
        if: github.event_name == 'workflow_dispatch'
        run: echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: |
            ghcr.io/${{ github.repository }}
      
      - name: Print INFO
        run: |
          echo "Tags:     ${{ steps.meta.outputs.tags }}
          echo "labels:   ${{ steps.meta.outputs.labels }}
        

